<?php defined('BASEPATH') or exit('No direct script access allowed');
date_default_timezone_set('Asia/Kolkata');
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
// $config['base_url'] = 'https://localhost/CodeIgniter-HMVC-AdminLTE';
$config['base_url'] = APP_URL;
//enable previous section access after payment
$config['is_allow_previous']=0; //1-allow,0-not allow
$config['is_allow_preview']=0; //1-allow,0-not allow
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
// $config['composer_autoload'] = 'vendor/autoload.php';
$config['composer_autoload'] = realpath(APPPATH . '../vendor/autoload.php');

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = (ENVIRONMENT !== 'production') ? 2 : 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/

if (isset($_SERVER["REQUEST_URI"]) && (isset($_SERVER['REQUEST_METHOD']) && ($_SERVER['REQUEST_METHOD'] == 'POST')))
{
	// Verify if POST Request is not for API
	$config['csrf_protection'] = (stripos($_SERVER["REQUEST_URI"],'/api/') === false) ? TRUE : FALSE;
}else {
	// Set CSRF Token True
    $config['csrf_protection'] = TRUE;
} 
//$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;

$config['csrf_exclude_uris'] = array('api/login','api/register','api​/forgotpwd','api/insert_mailbox','api/mailbox','api/mailboxes','api/stream','api​/streams​','api/application_form','api/application_forms','api/user_list/','api/upload','api/edit_user','api/user','api​/user​','api/queue_push','api/queue_pull','user/register','create_captcha','login','api/change_password','change-password','user/edit_profile','api/mobile_codes','api/mobile_code','check_captcha','check_user_exists','api/forgotpwd','forgot_password','otp_forgotpassword','api/otpverifyforgotpwd','api/updatepwdotp','otp_updateforgotpassword','check_verifylink','api/check_verifylink','api/nationalities','api/nationality','api/course','api/courses','api/specialization','api/specializations','api/campuses','api/campus','crm-admin/login','api_crmadmin/login','api/bloodgroups','get_bloodgroups','api/user_work_category','get_work_category','get_are_you_employed','api/user_working_place','get_working_place','api/user_gender_title','get_gender_title','api/user_gender','get_gender','api/user_social_status','get_social_status','get_nature_of_deformity','get_percentage_of_deformity','api/qualifying_degrees','api/qualifying_degree','api/spec_qualifying_degrees','api/spec_qualifying_degree','api/departments','api/department','api/faculties','api/faculty','api/personal_details','api/personal_detail','api/user_nature_deformity','api/get_nationality','api/get_nationality_single','have_you_taken_any_competitive_exam','api/applicant_details','api/applicant','btech','get_current_resident','get_parent_title','get_parent_occupation','get_advertisement_source','api/graduations','api/db_func_other_detail','api/db_func_competitive_detail','api/db_func_grad_detail','api/db_func_exp_detail','api/db_func_pub_detail','api/db_func_doc_detail','api/db_func_basic_detail','api/db_func_address_detail','api/db_func_payment_detail','get_eco_weaker_section','api/user_boards','api/user_board','get_board','api/user_mode_of_study','get_mode_of_study','api/hcma_branchs','get_hcma_studied_from_india','get_hcma_branchs','api/user_mode_of_study','get_mode_of_study','get_current_qualification_status','api/get_mtechrecampusprefer','api/get_mtechrecampusprefer_single','get_mtechrecampus_preference','api/get_mtechrespecializationprefer','api/get_mtechrespecializationprefer_single','api/get_mtechrereligion','api/get_mtechremothertong','api/countries','api/get_countries','api/db_func_appln_detail', 'api/db_func_campus_prefer_detail', 'api/db_func_city_prefer_detail', 'api/db_func_course_prefer_detail', 'api/db_func_parent_detail','get_yr_of_passing_schooling','api/db_func_course_detail','api/db_func_campus_detail','api/db_func_parent_detail','api/db_func_choice_dropdown','get_streams','get_degrees','api/db_func_schooling_detail','get_choice_dropdown','api/learn_second_lang','api/grad_univ','dde_form_preview','api/get_appln_form_id','api/check_applicant_appln','api/singlecoordinator','api/parent_titles','hcma_preview','get_course_prefer','api/db_func_call_dde','get_course_preference','api/db_func_call_dde','get_campus_preference','api/db_func_call_dde_campus','api/hcma_preference','get_hcma_preference','mtech','get_bmed_studied_from_india','get_bmed_resident_status','bmed_mphil_courses','api/bmed_mphil_courses','bmed_edu_status','parent_occupation','api/parent_occupation','api/get_applicantid','b-ed-m-ed-m-phil_preview','bscam_preview','api/shug_preference','api/course_preference','bba_studied_from_india','bba_resident_status','bba_edu_status','studied_from_india','resident_status','course_preference','bba_preview','shug_preview','qualification_status','api/qualification_status','api_crmadmin/get_user','user/payment_process','api/db_func_call_apg_course','api/db_func_call_apg_campus','get_apg_campus_preference','get_apg_course_preference','mba_preview','api/db_func_instruction','api/db_func_applicant_appln_detail','shpg','shpg_preview','api/shpg_basic_detail','api/shpg_preference','api/shpg_personal_detail','api/shpg_parent_detail','api/shpg_addressdet','api/shpg_academicdet','api/shpg_declaration','api/competitive_exam_list','api/tab_w_percentage','user/get_percentage_w_tab','thank_you','api/applicantstatus','api/job_sectors','job_sectors','api/bank_lists','api/bank_list','get_banks','get_spl_preferences_bsc','api/db_func_call_bsc','api/db_func_call_bsc_campus','get_campus_bsc','user/payment_details_online','get_schooling_details','api/db_func_qualification_status' , 'api/db_func_regcourse_dropdown' , 'regcourse_dropdown','api/thankyou_data','part-time-ug-pg_preview','advanced_pg_dp_form_preview','hspg_diploma_preview','api/declaration_apg','get_agrsci_pgm_level','api/db_func_call_agrisci_pgm_level','api/db_func_call_agrisci_course','get_agrisci_course_preference','api/upload_final_step','hsug_preview','hspg_ee_preview','api/query_categories','api/form_list','international_form','api/check_demo','api/mytickets','api/ticket_detail','get_fellowship_campus_preference','get_fellowship_course_preference','fellowship_preview','api/db_func_call_fellowship_campus','api/ticket_conversations','ticket_details','ticket_details/(:any)','api/fn_get_app_qualifications','api/form_wizards_list','api/form_wizard_list','tamilperayam_form_preview','api/db_func_call_tamil_course','api/appln_wizard_dtl','api/resident_category','api/relation_sponsor','phd-jan-preview','dde_jan_form_preview','api/db_func_choice_dropdown_international','api/examination','api/subject_list','api/examination_list','api/guardian_relationships','relationships','international-form/login','api/international_register','api/international_login','get_international_percentage_w_tab','api/upload_files','api/user_marking_scheme','upload-file','api/addressdet','del-uploaded-file','api/del_upload_file','api/payment_details','user/payment_details','user/payment_thank_you','api/upload_final','crm-admin/chart-demo','crm-admin/chart-demo2','crm-admin/bar-chart','crm-admin/bar-line-chart','crm-admin/doughnut-chart','crm-admin/time-chart');

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

/*
|--------------------------------------------------------------------------
| Set HMVC Modules Location
|--------------------------------------------------------------------------
|
*/
$config['modules_locations'] = array(
    APPPATH.'modules/' => '../modules/',
);

$config['copyright_initial_year'] = 2019;


$hostApiUrl = 'http://localhost/SRM-Online-Application-New/';

$config['api_urls'] = array('login'=>$hostApiUrl.'api/login',
'upload'=>$hostApiUrl.'api/upload',
'streams'=>$hostApiUrl.'api/streams',
'register'=>$hostApiUrl.'api/register',
'check_verifylink'=>$hostApiUrl.'api/check_verifylink',
'forgotpwd'=>$hostApiUrl.'api/forgotpwd',
'users'=>$hostApiUrl.'api/users',
'user'=>$hostApiUrl.'api/user',
'edit_user'=>$hostApiUrl.'api/edit_user',
'mailboxes'=>$hostApiUrl.'api/mailboxes',
'insert_mailbox'=>$hostApiUrl.'api/insert_mailbox',
'queue_push'=>$hostApiUrl.'api/queue_push',
'queue_pull'=>$hostApiUrl.'api/queue_pull',
'send_sms'=>$hostApiUrl.'api/send_sms',			
'mobile_codes'=>$hostApiUrl.'api/mobile_codes',			
'states'=>$hostApiUrl.'api/states',			
'cities'=>$hostApiUrl.'api/cities',	
'districts'=>$hostApiUrl.'api/districts',
'degrees'=>$hostApiUrl.'api/degrees',			
'discardmail'=>$hostApiUrl.'api/discardmail',	
'discardcounts'=>$hostApiUrl.'api/discardcounts',	
'change_password'=>$hostApiUrl.'api/change_password',
'otpverifyforgotpwd'=>$hostApiUrl.'api/otpverifyforgotpwd',
'updatepwdotp'=>$hostApiUrl.'api/updatepwdotp',
'nationalities'=>$hostApiUrl.'api/nationalities',
'courses'=>$hostApiUrl.'api/courses',
'specializations'=>$hostApiUrl.'api/specializations',
'campuses'=>$hostApiUrl.'api/campuses',
'crm_login'=>$hostApiUrl.'api_crmadmin/login',
'bloodgroups'=>$hostApiUrl.'api/bloodgroups',
'app_courses'=>$hostApiUrl.'api/app_courses',
'user_work_category'=>$hostApiUrl.'api/user_work_category',
'user_working_place'=>$hostApiUrl.'api/user_working_place',
'user_gender_title'=>$hostApiUrl.'api/user_gender_title',
'user_gender'=>$hostApiUrl.'api/user_gender',
'user_social_status'=>$hostApiUrl.'api/user_social_status',
'upload_files'=>$hostApiUrl.'api/upload_files',
'wizard_api'=>$hostApiUrl.'api/wizard_api',
'qualifying_degrees'=>$hostApiUrl.'api/qualifying_degrees',
'spec_qualifying_degrees'=>$hostApiUrl.'api/spec_qualifying_degrees',
'departments'=>$hostApiUrl.'api/departments',
'faculties'=>$hostApiUrl.'api/faculties',
'personal_detail'=>$hostApiUrl.'api/personal_detail',
'other_universities'=>$hostApiUrl.'api/other_universities',
'user_marking_scheme'=>$hostApiUrl.'api/user_marking_scheme',
'competitive_exams'=>$hostApiUrl.'api/competitive_exams',
'upload_filelist'=>$hostApiUrl.'api/upload_filelist',
'addressdet'=>$hostApiUrl.'api/addressdet',
'del_upload_file'=>$hostApiUrl.'api/del_upload_file',
'user_nature_deformity'=>$hostApiUrl.'api/user_nature_deformity',
'get_nationality'=>$hostApiUrl.'api/get_nationality',
'applicant'=>$hostApiUrl.'api/applicant',
'phd_acdemic_dtl'=>$hostApiUrl.'api/phd_acdemic_dtl',
'applicant_publication_dets'=>$hostApiUrl.'api/applicant_publication_dets',
'applicant_prof_exps'=>$hostApiUrl.'api/applicant_prof_exps',
'applicant_graduations'=>$hostApiUrl.'api/applicant_graduations',
'applicant_other_details'=>$hostApiUrl.'api/applicant_other_details',
'applicant_comp_exams'=>$hostApiUrl.'api/applicant_comp_exams',
'wizard_api_dist_edu'=>$hostApiUrl.'api/wizard_api_dist_edu',
'mtechreearchbasicdet'=>$hostApiUrl.'api/mtechreearchbasicdet',
'mtechrecampusprefer'=>$hostApiUrl.'api/get_mtechrecampusprefer',
'mtechrespecializationprefer'=>$hostApiUrl.'api/get_mtechrespecializationprefer',
'get_mtechrereligion'=>$hostApiUrl.'api/get_mtechrereligion',
'get_mtechremothertong'=>$hostApiUrl.'api/get_mtechremothertong',
'religions'=>$hostApiUrl.'api/religions',
'mother_tongues'=>$hostApiUrl.'api/mother_tongues',
'advertisement_sources'=>$hostApiUrl.'api/advertisement_sources',
'branchs'=>$hostApiUrl.'api/branchs',
'btech_basic_detail'=>$hostApiUrl.'api/btech_basic_detail',
'graduations'=>$hostApiUrl.'api/graduations',
'wizard_api_parent'=>$hostApiUrl.'api/wizard_api_parent',
'btech_personal_detail'=>$hostApiUrl.'api/btech_personal_detail',
'db_func_other_detail'=>$hostApiUrl.'api/db_func_other_detail',
'db_func_competitive_detail'=>$hostApiUrl.'api/db_func_competitive_detail',
'db_func_grad_detail'=>$hostApiUrl.'api/db_func_grad_detail',
'db_func_exp_detail'=>$hostApiUrl.'api/db_func_exp_detail',
'db_func_pub_detail'=>$hostApiUrl.'api/db_func_pub_detail',
'db_func_doc_detail'=>$hostApiUrl.'api/db_func_doc_detail',
'db_func_basic_detail'=>$hostApiUrl.'api/db_func_basic_detail',
'db_func_address_detail'=>$hostApiUrl.'api/db_func_address_detail',
'db_func_payment_detail'=>$hostApiUrl.'api/db_func_payment_detail',
'dis_edu_academic_api'=>$hostApiUrl.'api/dis_edu_academic_api',
'user_boards'=>$hostApiUrl.'api/user_boards',
'user_mode_of_study'=>$hostApiUrl.'api/user_mode_of_study',
'hcma_branchs'=>$hostApiUrl.'api/hcma_branchs',
'hcma_basic_detail'=>$hostApiUrl.'api/hcma_basic_detail',
'hcma_personal_detail'=>$hostApiUrl.'api/hcma_personal_detail',
'hcma_addressdet'=>$hostApiUrl.'api/hcma_addressdet',
'hcma_academicdet'=>$hostApiUrl.'api/hcma_academicdet',
'hcma_declaration'=>$hostApiUrl.'api/hcma_declaration',
'countries'=>$hostApiUrl.'api/countries',
'db_func_appln_detail'=>$hostApiUrl.'api/db_func_appln_detail',
'db_func_campus_prefer_detail'=>$hostApiUrl.'api/db_func_campus_prefer_detail',
'db_func_city_prefer_detail'=>$hostApiUrl.'api/db_func_city_prefer_detail',
'db_func_course_prefer_detail'=>$hostApiUrl.'api/db_func_course_prefer_detail',
'db_func_parent_detail'=>$hostApiUrl.'api/db_func_parent_detail',
'db_func_course_detail'=>$hostApiUrl.'api/db_func_course_detail',
'db_func_campus_detail'=>$hostApiUrl.'api/db_func_campus_detail',
'hcma_parent_detail'=>$hostApiUrl.'api/hcma_parent_detail',
'db_func_choice_dropdown'=>$hostApiUrl.'api/db_func_choice_dropdown',
'db_func_schooling_detail'=>$hostApiUrl.'api/db_func_schooling_detail',
'btech_parent_detail'=>$hostApiUrl.'api/btech_parent_detail',
'learn_second_lang'=>$hostApiUrl.'api/learn_second_lang',
'grad_univ'=>$hostApiUrl.'api/grad_univ',
'btech_academic_detail'=>$hostApiUrl.'api/btech_academic_detail',
'db_func_schooling_detail'=>$hostApiUrl.'api/db_func_schooling_detail',
'btech_declaration_detail'=>$hostApiUrl.'api/btech_declaration_detail',
'declaration_dde'=>$hostApiUrl.'api/declaration_dde',
'check_applicant_appln'=>$hostApiUrl.'api/check_applicant_appln',
'get_appln_form_id'=>$hostApiUrl.'api/get_appln_form_id',
'mtechresearch_personal_detail'=>$hostApiUrl.'api/mtechresearch_personal_detail',
'mtechresearch_acdemic_dtl'=>$hostApiUrl.'api/mtechresearch_acdemic_dtl',
'singlecoordinator'=>$hostApiUrl.'api/singlecoordinator',
'mtechresearch_declaration_dtl'=>$hostApiUrl.'api/mtechresearch_declaration_dtl',
'mtechresearch_parent_detail'=>$hostApiUrl.'api/mtechresearch_parent_detail',
'parent_titles'=>$hostApiUrl.'api/parent_titles',
'mtech_basic_detail'=>$hostApiUrl.'api/mtech_basic_detail',
'mtech_personal_detail'=>$hostApiUrl.'api/mtech_personal_detail',
'mtech_parent_detail'=>$hostApiUrl.'api/mtech_parent_detail',
'mtech_academic_detail'=>$hostApiUrl.'api/mtech_academic_detail',
'mtech_declaration_detail'=>$hostApiUrl.'api/mtech_declaration_detail',
'hcma_preference'=>$hostApiUrl.'api/hcma_preference',
'db_func_call_dde'=>$hostApiUrl.'api/db_func_call_dde',
'db_func_call_dde_campus'=>$hostApiUrl.'api/db_func_call_dde_campus',
'basic_detail_bsc_am'=>$hostApiUrl.'api/basic_detail_bsc_am',
'personal_detail_bsc_am'=>$hostApiUrl.'api/personal_detail_bsc_am',
'bsc_parent_detail'=>$hostApiUrl.'api/bsc_parent_detail',
'bsc_academic_detail'=>$hostApiUrl.'api/bsc_academic_detail',
'bmed_basic_detail'=>$hostApiUrl.'api/bmed_basic_detail',
'bmed_mphil_courses'=>$hostApiUrl.'api/bmed_mphil_courses',
'bmed_personal_detail'=>$hostApiUrl.'api/bmed_personal_detail',
'bmed_parent_detail'=>$hostApiUrl.'api/bmed_parent_detail',
'bmed_addressdet'=>$hostApiUrl.'api/bmed_addressdet',
'bmed_academicdet'=>$hostApiUrl.'api/bmed_academicdet',
'bmed_declaration'=>$hostApiUrl.'api/bmed_declaration',
'declaration_bscam'=>$hostApiUrl.'api/declaration_bscam',
'parent_occupation'=>$hostApiUrl.'api/parent_occupation',
'barch_basic_detail'=>$hostApiUrl.'api/barch_basic_detail',
'barch_personal_detail'=>$hostApiUrl.'api/barch_personal_detail',
'barch_parent_detail'=>$hostApiUrl.'api/barch_parent_detail',
'barch_acdemic_dtl'=>$hostApiUrl.'api/barch_acdemic_dtl',
'get_applicantid'=>$hostApiUrl.'api/get_applicantid',
'barch_declaration_detail'=>$hostApiUrl.'api/barch_declaration_detail',
'shug_basic_detail'=>$hostApiUrl.'api/shug_basic_detail',
'shug_preference'=>$hostApiUrl.'api/shug_preference',
'shug_personal_detail'=>$hostApiUrl.'api/shug_personal_detail',
'get_user'=>$hostApiUrl.'api_crmadmin/get_user',
'shug_parent_detail'=>$hostApiUrl.'api/shug_parent_detail',
'shug_addressdet'=>$hostApiUrl.'api/shug_addressdet',
'shug_academicdet'=>$hostApiUrl.'api/shug_academicdet',
'shug_declaration'=>$hostApiUrl.'api/shug_declaration',
'bba_basic_detail'=>$hostApiUrl.'api/bba_basic_detail',
'course_preference'=>$hostApiUrl.'api/course_preference',
'bba_personal_detail'=>$hostApiUrl.'api/bba_personal_detail',
'bba_parent_detail'=>$hostApiUrl.'api/bba_parent_detail',
'bba_addressdet'=>$hostApiUrl.'api/bba_addressdet',
'bba_academicdet'=>$hostApiUrl.'api/bba_academicdet',
'bba_declaration'=>$hostApiUrl.'api/bba_declaration',
'qualification_status'=>$hostApiUrl.'api/qualification_status',
'basic_details_apg'=>$hostApiUrl.'api/basic_details_apg',
'personal_detail_apg'=>$hostApiUrl.'api/personal_detail_apg',
'db_func_call_apg_course'=>$hostApiUrl.'api/db_func_call_apg_course',
'db_func_call_apg_campus'=>$hostApiUrl.'api/db_func_call_apg_campus',
'apg_parent_detail'=>$hostApiUrl.'api/apg_parent_detail',
'mba_basic_detail'=>$hostApiUrl.'api/mba_basic_detail',
'mba_personal_detail'=>$hostApiUrl.'api/mba_personal_detail',
'mba_parent_detail'=>$hostApiUrl.'api/mba_parent_detail',
'mba_addressdet'=>$hostApiUrl.'api/mba_addressdet',
'mba_academicdet'=>$hostApiUrl.'api/mba_academicdet',
'mba_declaration'=>$hostApiUrl.'api/mba_declaration',
'db_func_instruction'=>$hostApiUrl.'api/db_func_instruction',
'db_func_applicant_appln_detail'=>$hostApiUrl.'api/db_func_applicant_appln_detail',
'shpg_basic_detail'=>$hostApiUrl.'api/shpg_basic_detail',
'shpg_preference'=>$hostApiUrl.'api/shpg_preference',
'shpg_personal_detail'=>$hostApiUrl.'api/shpg_personal_detail',
'shpg_parent_detail'=>$hostApiUrl.'api/shpg_parent_detail',
'shpg_addressdet'=>$hostApiUrl.'api/shpg_addressdet',
'shpg_academicdet'=>$hostApiUrl.'api/shpg_academicdet',
'shpg_declaration'=>$hostApiUrl.'api/shpg_declaration',
'competitive_exam_list'=>$hostApiUrl.'api/competitive_exam_list',    
'tab_w_percentage'=>$hostApiUrl.'api/tab_w_percentage',
'applicantstatus'=>$hostApiUrl.'api/applicantstatus',
'bank_lists'=>$hostApiUrl.'api/bank_lists',
'bank_list'=>$hostApiUrl.'api/bank_list',
'payment_details'=>$hostApiUrl.'api/payment_details',
'job_sectors'=>$hostApiUrl.'api/job_sectors',
'phd_final_step'=>$hostApiUrl.'api/phd_final_step',
'db_func_call_bsc'=>$hostApiUrl.'api/db_func_call_bsc',
'db_func_call_bsc_campus'=>$hostApiUrl.'api/db_func_call_bsc_campus',
'db_func_qualification_status'=>  $hostApiUrl.'api/db_func_qualification_status',
'db_func_regcourse_dropdown'=>  $hostApiUrl.'api/db_func_regcourse_dropdown',
'thankyou_data'=>  $hostApiUrl.'api/thankyou_data',
'part_time_ug_pg_basic_detail'=>$hostApiUrl.'api/part_time_ug_pg_basic_detail',
'part_time_ug_pg_personal_detail'=>$hostApiUrl.'api/part_time_ug_pg_personal_detail',
'part_time_ug_pg_parent_detail'=>$hostApiUrl.'api/part_time_ug_pg_parent_detail',
'part_time_ug_pg_addressdet'=>$hostApiUrl.'api/part_time_ug_pg_addressdet',
'part_time_ug_pg_academicdet'=>$hostApiUrl.'api/part_time_ug_pg_academicdet',
'part_time_ug_pg_declaration'=>$hostApiUrl.'api/part_time_ug_pg_declaration',
'apg_academic_detail'=>$hostApiUrl.'api/apg_academic_detail',
'march_basic_detail'=>$hostApiUrl.'api/march_basic_detail',
'march_personal_detail'=>$hostApiUrl.'api/march_personal_detail',
'march_parent_detail'=>$hostApiUrl.'api/march_parent_detail',
'march_acdemic_dtl'=>$hostApiUrl.'api/march_acdemic_dtl',
'declaration_apg'=>$hostApiUrl.'api/declaration_apg',
'march_declaration_detail'=>$hostApiUrl.'api/march_declaration_detail',
'hspg_diploma_basic_detail'=>$hostApiUrl.'api/hspg_diploma_basic_detail',
'hspg_diploma_personal_detail'=>$hostApiUrl.'api/hspg_diploma_personal_detail',
'hspg_diploma_parent_detail'=>$hostApiUrl.'api/hspg_diploma_parent_detail',
'hspg_diploma_addressdet'=>$hostApiUrl.'api/hspg_diploma_addressdet',
'hspg_diploma_academicdet'=>$hostApiUrl.'api/hspg_diploma_academicdet',
'hspg_diploma_declaration'=>$hostApiUrl.'api/hspg_diploma_declaration',
'basic_details_agrisci'=>$hostApiUrl.'api/basic_details_agrisci',
'personal_detail_agrisci'=>$hostApiUrl.'api/personal_detail_agrisci',
'agrisci_parent_detail'=>$hostApiUrl.'api/agrisci_parent_detail',
'agrisci_academic_detail'=>$hostApiUrl.'api/agrisci_academic_detail',
'declaration_agrisci'=>$hostApiUrl.'api/declaration_agrisci',
'db_func_call_agrisci_pgm_level'=>$hostApiUrl.'api/db_func_call_agrisci_pgm_level',
'db_func_call_agrisci_course'=>$hostApiUrl.'api/db_func_call_agrisci_course',
'upload_final_step'=>$hostApiUrl.'api/upload_final_step',
'hsug_basic_detail'=>$hostApiUrl.'api/hsug_basic_detail',
'hsug_personal_detail'=>$hostApiUrl.'api/hsug_personal_detail',
'hsug_parent_detail'=>$hostApiUrl.'api/hsug_parent_detail',
'hsug_addressdet'=>$hostApiUrl.'api/hsug_addressdet',
'hsug_academicdet'=>$hostApiUrl.'api/hsug_academicdet',
'hsug_declaration'=>$hostApiUrl.'api/hsug_declaration',
'upload_final'=>$hostApiUrl.'api/upload_final',
'law_basic_detail'=>$hostApiUrl.'api/law_basic_detail',
'law_personal_detail'=>$hostApiUrl.'api/law_personal_detail',
'law_parent_detail'=>$hostApiUrl.'api/law_parent_detail',
'law_acdemic_dtl'=>$hostApiUrl.'api/law_acdemic_dtl',
'law_declaration_detail'=>$hostApiUrl.'api/law_declaration_detail',
'hspg_ee_basic_detail'=>$hostApiUrl.'api/hspg_ee_basic_detail',
'hspg_ee_personal_detail'=>$hostApiUrl.'api/hspg_ee_personal_detail',
'hspg_ee_parent_detail'=>$hostApiUrl.'api/hspg_ee_parent_detail',
'hspg_ee_addressdet'=>$hostApiUrl.'api/hspg_ee_addressdet',
'hspg_ee_academicdet'=>$hostApiUrl.'api/hspg_ee_academicdet',
'hspg_ee_declaration'=>$hostApiUrl.'api/hspg_ee_declaration',
'query_categories'=>$hostApiUrl.'api/query_categories',
'form_list'=>$hostApiUrl.'api/form_list',
'save_query'=>$hostApiUrl.'api/save_query',
'mytickets'=>$hostApiUrl.'api/mytickets',
'ticket_detail'=>$hostApiUrl.'api/ticket_detail',
'ticket_conversations'=>$hostApiUrl.'api/ticket_conversations',
'save_conversation'=>$hostApiUrl.'api/save_conversation',
'international_personal_detail'=>$hostApiUrl.'api/international_personal_detail',
'basic_details_fellowship'=>$hostApiUrl.'api/basic_details_fellowship',
'personal_detail_fellowship'=>$hostApiUrl.'api/personal_detail_fellowship',
'fellowship_parent_detail'=>$hostApiUrl.'api/fellowship_parent_detail',
'fellowship_academic_detail'=>$hostApiUrl.'api/fellowship_academic_detail',
'declaration_fellowship'=>$hostApiUrl.'api/declaration_fellowship',
'db_func_call_fellowship_course'=>$hostApiUrl.'api/db_func_call_fellowship_course',
'db_func_call_fellowship_campus'=>$hostApiUrl.'api/db_func_call_fellowship_campus',
'afih_basic_detail'=>$hostApiUrl.'api/afih_basic_detail',
'afih_personal_detail'=>$hostApiUrl.'api/afih_personal_detail',
'afih_parent_detail'=>$hostApiUrl.'api/afih_parent_detail',
'afih_addressdet'=>$hostApiUrl.'api/afih_addressdet',
'afih_academicdet'=>$hostApiUrl.'api/afih_academicdet',
'afih_declaration'=>$hostApiUrl.'api/afih_declaration',
'fn_get_app_qualifications'=>   $hostApiUrl.'api/fn_get_app_qualifications',
'form_wizards_list'=>$hostApiUrl.'api/form_wizards_list',
'basic_details_tamil'=>$hostApiUrl.'api/basic_details_tamil',
'personal_detail_tamil'=>$hostApiUrl.'api/personal_detail_tamil',
'tamil_parent_detail'=>$hostApiUrl.'api/tamil_parent_detail',
'tamil_academic_detail'=>$hostApiUrl.'api/tamil_academic_detail',
'declaration_tamil'=>$hostApiUrl.'api/declaration_tamil',
'db_func_call_tamil_course'=>$hostApiUrl.'api/db_func_call_tamil_course',
'appln_wizard_dtl'=>$hostApiUrl.'api/appln_wizard_dtl',
'phd_jan_acdemic_dtl'=>$hostApiUrl.'api/phd_jan_acdemic_dtl',
'phd_jan_final_step'=>$hostApiUrl.'api/phd_jan_final_step',
'wizard_api_phd_jan'=>$hostApiUrl.'api/wizard_api_phd_jan',
'resident_category'=>$hostApiUrl.'api/resident_category',
'relation_sponsor'=>$hostApiUrl.'api/relation_sponsor',
'international_basic_detail'=>$hostApiUrl.'api/international_basic_detail',
'international_address_detail'=>$hostApiUrl.'api/international_address_detail',
'declaration_intl'=>$hostApiUrl.'api/declaration_intl',
'wizard_api_parent_edu'=>$hostApiUrl.'api/wizard_api_parent_edu',
'wizard_api_dist_edu_jan'=>$hostApiUrl.'api/wizard_api_dist_edu_jan',
'dis_edu_academic_jan'=>$hostApiUrl.'api/dis_edu_academic_jan',
'declaration_dde_jan'=>$hostApiUrl.'api/declaration_dde_jan',
'mtechreearchbasicdet_jan'=>$hostApiUrl.'api/mtechreearchbasicdet_jan',
'mtechresearch_personal_detail_jan'=>$hostApiUrl.'api/mtechresearch_personal_detail_jan',
'mtechresearch_acdemic_dtl_jan'=>$hostApiUrl.'api/mtechresearch_acdemic_dtl_jan',
'mtechresearch_declaration_jan'=>$hostApiUrl.'api/mtechresearch_declaration_jan',
'mtechresearch_parent_detail_jan'=>$hostApiUrl.'api/mtechresearch_parent_detail_jan',
'db_func_choice_dropdown_international'=>$hostApiUrl.'api/db_func_choice_dropdown_international',
'international_parent_detail'=>$hostApiUrl.'api/international_parent_detail',
'examination_list'=>$hostApiUrl.'api/examination_list',
'subject_list'=>$hostApiUrl.'api/subject_list',
'international_academic_detail'=>$hostApiUrl.'api/international_academic_detail',
'guardian_relationships'=>$hostApiUrl.'api/guardian_relationships',
'international_register'=>$hostApiUrl.'api/international_register',
'international_login'=>$hostApiUrl.'api/international_login',
'alltickets'=>$hostApiUrl.'api_crmadmin/alltickets',
'ticket_count'=>$hostApiUrl.'api_crmadmin/ticketscount',
'payment_details_failure'=>$hostApiUrl.'api/payment_details_failure',
);

$config['crmadminapi_urls'] = array('login'=>$hostApiUrl.'api_crmadmin/login');

$config['gender_title'] = array(1=>'MR', 2=>'MRS', 3=>'MISS');
$config['gender'] = array(1=>'Male', 2=>'Female', 3=>'Transgender');
$config['social_status'] = array(1=>'General', 2=>'General / EWS', 3=>'OBC', 4=>'ST', 5=>'SC');
$config['nature_of_deformity'] = array(1=>'Locomotor / Orthopaedic Disability', 2=>'Visual Impairment', 3=>'Multiple Disabilities', 4=>'Mental Retardation', 5=>'Speech and Hearing Disability');
$config['percentage_of_deformity'] = array(1=>'10%', 2=>'20%', 3=>'30%',4=>'40%',5=>'50%',6=>'60%',7=>'70%',8=>'80%',9=>'90%',10=>'100%');
$config['are_you_employed'] = array('yes'=>'Yes', 'no'=>'No');
$config['are_you_differenlty_abled'] = array('yes'=>'Yes', 'no'=>'No');
$config['have_you_taken_any_competitive_exam'] = array('yes'=>'Yes', 'no'=>'No');
$config['studied_from_india'] = array('yes'=>'Yes', 'no'=>'No');
$config['template_logo_image_path']='assets\common\images\srm-logo-blue.png';
$config['current_resident_tn'] = array('yes'=>'Yes', 'no'=>'No');
$config['parent_title'] = array(72=>'MR', 75=>'DR', 276=>'Late');
$config['mother_title'] = array(73=>'MRS', 75=>'DR', 276=>'Late');
$config['parent_occupation'] = array(4=>'Business', 3=>'Defence', 2=>'Government Sector', 6=>'Homemaker', 1=>'Private Sector', 5=>'Retired', 7=>'Other');
$config['eco_weaker_section'] = array('yes'=>'Yes', 'no'=>'No');
$config['hostel_accommodation'] = array('yes'=>'Yes', 'no'=>'No');
$config['current_qualification_status'] = array('twelfth'=>'Twelfth / 3 year Diploma Passed', 'graduation'=>'Graduation Passed');
$config['resident_category'] = array('non-resident-indian'=>'Non Resident Indian', 'foreign'=>'Foreign');
$config['yr_of_passing_schooling'] =  array(1950=>1950,1951=>1951,1952=>1952,1953=>1953,1954=>1954,1955=>1955,1956=>1956,1957=>1957,1958=>1958,1959=>1959,1960=>1960,1961=>1961,1962=>1962,1963=>1963,1964=>1964,1965=>1965,1966=>1966,1967=>1967,1968=>1968,1969=>1969,1970=>1970,1971=>1971,1972=>1972,1973=>1973,1974=>1974,1975=>1975,1976=>1976,1977=>1977,1978=>1978,1979=>1979,1980=>1980,1981=>1981,1982=>1982,1983=>1983,1984=>1984,1985=>1985,1986=>1986,1987=>1987,1988=>1988,1989=>1989,1990=>1990,1991=>1991,1992=>1992,1993=>1993,1994=>1994,1995=>1995,1996=>1996,1997=>1997,1998=>1998,1999=>1999,2000=>2000,2001=>2001,2002=>2002,2003=>2003,2004=>2004,2005=>2005,2006=>2006,2007=>2007,2008=>2008,2009=>2009,2010=>2010,2011=>2011,2012=>2012,2013=>2013,2014=>2014,2015=>2015,2016=>2016,2017=>2017,2018=>2018,2019=>2019,2020=>2020);
$config['thank_you_srm_logo'] = $hostApiUrl."assets/common/images/srm-logo-blue-email.png";
$config['tenth_status'] = array('0'=>'Awaited', '1'=>'Declared');
$config['hcma_current_qualification_status'] = array('0'=>'Twelth Pursuing', '1'=>'Twelth Passed');
$config['form_id'] = array('phd_form'=>APP_FORM_ID_PHD);
$config['comp_exam_qualified_status'] = array(0=>'Not Qualified', 1=>'Qualified');
$config['is_work_experience_status'] = array('yes'=>'Yes', 'no'=>'No');
$config['bmed_mphil_qualifications'] = array('ug_pur'=>'GraduationPursuing', 'ug_pass'=>'Graduation Passed','pg_pur'=>'Post Graduation Pursuing','pg_pass'=>'Post Graduation Passed');
$config['cpg_score'] = array(
    '57' => array('min'=>'33','max'=>'100'),
    '35' => array('min'=>'3.3','max'=>'10'),
    '36' => array('min'=>'3','max'=>'9'),
    '37' => array('min'=>'2','max'=>'7'),
    '38' => array('min'=>'1','max'=>'4'),
    '34' => array('min'=>'33','max'=>'100')
);
$config['bba_qualifications'] = array('0'=>'12th Appearing ', '1'=>'12th Completed');
$config['law_qualifications'] = array('0'=>'Pursuing ', '1'=>'Completed');
$config['hsug_qualifications'] = array('0'=>'12th Appearing ', '1'=>'12th Completed');
$config['form_path']=array(
    27 => 'mtech',
    9 => 'dis-education',
    22 => 'phd',
    18 => 'mtechresearch',
    13 => 'hcma',
     5 => 'b-ed-m-ed-m-phil',
    23 => 'shug',
    26 => 'mba',
    4 => 'bba',
    7=>'btech',
    6 =>'bsc-am',
    3 =>'barch',
    19 =>'part-time-ug-pg-courses',
    17=>'march',
	1=>'pgdplifescience',
    12=>'hspg_diploma',
	2=>'agrisci',
    16=>'law',
    10=>'hspg_ee',
	11=>'hsug',
	25=>'fellowship',
    35=>'afih',
	28=>'tamilperayam',
    21=>'phd-jan',
    30 => 'dis-education-jan',
    29 => 'mtechresearch-jan',
    15 => 'international_form',
);

$config['form_payment_mode']=array(CASH => 'CASH',DD => 'DD',CHEQUE => 'CHEQUE',ONLINE => 'ONLINE');

$config['application_status']=array(312 => 'Inprogress',313 => 'Completed');

// A2557 Added
$config['form_path_preview']=array(22 => 'phd-preview',21 => 'phd-jan-preview',9 => 'dde_form_preview',30 => 'dde_jan_form_preview',6=>'bscam_preview',2=>'agrisci_form_preview',1=>'advanced_pg_dp_form_preview',25=>'fellowship_preview',13=>'hcma_preview',5=>'b-ed-m-ed-m-phil_preview',23=>'shug_preview',26=>'mba_preview',4=>'bba_preview',7=>'btech-preview',3=>'barch_form_preview',19=>'part-time-ug-pg_preview',17=>'march_form_preview',12=>'hspg_diploma_preview',16=>'law_form_preview',10=>'hspg_ee_preview',11=>'hsug_preview',35=>'afih_preview',28=>'tamilperayam_form_preview',29=>'mtechresearch-jan-preview',18=>'mtechresearch-preview',15=>'international-form-preview',27=>'mtech-preview');

$config['app_sequences']=array(
    27 => "nextval('admission.admission_appln_no_mtech_seq')",
    9 => "nextval('admission.admission_appln_no_dde_seq')",
    22 => "nextval('admission.admission_appln_no_phd_seq')",
    18 => '',
    13 => "nextval('admission.admission_appln_no_hotel_catering_seq')",
    5 => "nextval('admission.admission_appln_no_bed_med_mphil_seq')",
    23 => "nextval('admission.admission_appln_no_science_and_humanities_seq')",
    26 => "nextval('admission.admission_appln_no_mba_seq')",
    4 => "nextval('admission.admission_appln_no_bba_seq')",
    7=>"nextval('admission.admission_appln_no_btech_seq')",
    6 =>"nextval('admission.admission_appln_no_bsc_aircraft_seq')",
    3 =>"nextval('admission.admission_appln_no_barch_bdesign_seq')",
    17=>"nextval('admission.admission_appln_no_march_seq')",
    19=>"nextval('admission.admission_appln_no_parttime_ugpg_seq')",
    1=>"nextval('admission.admission_appln_no_advanced_pg_dip_seq')",
	2=>"nextval('admission.admission_appln_no_agricultural_seq')",
    12=>"nextval('admission_appln_no_health_science_non_entrance_seq')",
    16=>"nextval('admission.admission_appln_no_law_seq')",
	11=>"nextval('admission.admission_appln_no_health_science_ug_seq')",
    10=>"nextval('admission_appln_no_health_science_pg_seq')",
	25=>"nextval('admission_appln_no_fellowship_program_seq')",
    35=>"nextval('admission.admission_appln_no_afih_seq')",
	28 => '',
    30 => '',
    29 => '',
    15 => '',
);

$config['high_edu'] = array(
    SCHOOLING_ID_TENTH => array(SCHOOLING_ID_EIGHTH=>'Class 8th',SCHOOLING_ID_NINTH =>'Class 9th',SCHOOLING_ID_TENTH=>'Class 10th'),
    SCHOOLING_ID_TWELFTH=> array(SCHOOLING_ID_TWELFTH=>'Class 12th'),
    GRADUATION_UG_ID => array(GRADUATION_UG_ID=>'Graduation')
);
$config['agrisci_current_qualification_status'] = array('1'=>'Twelth Pursuing', '2'=>'Twelth Passed');

$config['index_restriction_agrisci']=array(107=>0,108=>1,109=>2,110=>3,111=>4,112=>5,113=>6);

// Tamil Perayram to get the degree value
$config['tamilperayam_degree'] = array('56'=>'Certificate', '43'=>'Diploma');
// allowed ip list
$config['allowed_ip_list']=array('172.16.0.10');