<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$config['TEST_CLIENT_VALIDATION_FILE'] = "TEST Client Validation";
defined('TEST_CLIENT_VALIDATION')  OR define('TEST_CLIENT_VALIDATION', "testclie");
defined('EMAIL_MAXLENGTH')  OR define('EMAIL_MAXLENGTH', 100);
defined('EMAIL_MATCH') OR define('EMAIL_MATCH','The entered alternate email id should not be equal to primary email id');
defined('EMAIL_MATCH_FATHER') OR define('EMAIL_MATCH_FATHER','The entered father email id should not be equal to mother email id');
defined('EMAIL_MATCH_MOTHER') OR define('EMAIL_MATCH_MOTHER','The entered mother email id should not be equal to father email id');
defined('PHONE_MATCH_MOTHER') OR define('PHONE_MATCH_MOTHER','The entered mother phone no should not be equal to father phone no');
defined('PHONE_MATCH_FATHER') OR define('PHONE_MATCH_FATHER','The entered father phone no should not be equal to mother phone no');
defined('PHONE_MATCH_GUARDIAN') OR define('PHONE_MATCH_GUARDIAN','The entered guardian phone no should not be equal to parents no');
defined('EMAIL_MATCH_GUARDIAN') OR define('EMAIL_MATCH_GUARDIAN','The entered guardian email should not be equal to parents email');
defined('EMAIL_MATCH_SEC_GUARDIAN') OR define('EMAIL_MATCH_SEC_GUARDIAN','The entered guardian email should not be equal to parents/primary guardian email');defined('CGPA_MAXLENGTH') OR define('CGPA_MAXLENGTH',6);
defined('DDE_TWELFTH_YOP') OR define('DDE_TWELFTH_YOP','The year of passing twelfth should be greater & should not be equal to year of passing tenth');
defined('DDE_GRADUATION_YOP') OR define('DDE_GRADUATION_YOP','The graduation year of passing should not be less than year of passing twelfth');
defined('PHONE_ALT_UNIQUE') OR define('PHONE_ALT_UNIQUE','The entered phone should not be equal to alternate phone no');

defined('NRI_FOREIGN')OR define('NRI_FOREIGN','NRI and Foreign Students please go to the below link to proceed further.');
defined('NRI_FOREIGN_URL')OR define('NRI_FOREIGN_URL','https://intlapplications.srmist.edu.in/international-application-form-2020.');
defined ('IS_AGREE_INFO') OR define ( 'IS_AGREE_INFO' , 'Please note that you have selected "YES" for the above which implies you are eligible to seek admission under domestic category. It is the sole responsibility of the candidate to ensure that he/she is applying under the right category.');

/* Form Field Validation message start here */
defined('REQD_CHOOSE_DEGREE_MSG')OR define('REQD_CHOOSE_DEGREE_MSG','Please Choose Degree');
defined('REQD_SELECT_GRAD_STATUS_MSG')OR define('REQD_SELECT_GRAD_STATUS_MSG','Please Select Status Yes/No');
defined('REQD_SELECT_STUDIED_RESIDENT_MSG')OR define('REQD_SELECT_STUDIED_RESIDENT_MSG','Please Select Studied Resident');
defined('REQD_SELECT_RESIDENT_CATEGORY_MSG')OR define('REQD_SELECT_RESIDENT_CATEGORY_MSG','Please Choose Resident Category');
defined('REQD_SPONSOR_NAME_MSG')OR define('REQD_SPONSOR_NAME_MSG','Please Enter Sponsor Name');
defined('REQD_CHOOSE_SPONSOR_RELATION_MSG')OR define('REQD_CHOOSE_SPONSOR_RELATION_MSG','Please Choose Sponsor Relationship');
defined('REQD_SELECT_RESIDENT_STATUS_MSG')OR define('REQD_SELECT_RESIDENT_STATUS_MSG','Please Select Resident Status');
defined('REQD_CHECK_CONFIRM_MSG')OR define('REQD_CHECK_CONFIRM_MSG','Please check confirm');
defined('REQD_SELECT_PRG_MSG')OR define('REQD_SELECT_PRG_MSG','Select Level of Program');
defined('REQD_SELECT_STREAM_PREFERENCE1_MSG')OR define('REQD_SELECT_STREAM_PREFERENCE1_MSG','Please Choose Stream Preference 1');
defined('REQD_SELECT_STREAM_PREFERENCE2_MSG')OR define('REQD_SELECT_STREAM_PREFERENCE2_MSG','Please Choose Stream Preference 2');
defined('REQD_SELECT_STREAM_PREFERENCE3_MSG')OR define('REQD_SELECT_STREAM_PREFERENCE3_MSG','Please Choose Stream Preference 3');
defined('REQD_SELECT_DEGREE_PREFERENCE1_MSG')OR define('REQD_SELECT_DEGREE_PREFERENCE1_MSG','Please Choose Degree Preference 1');
defined('REQD_SELECT_DEGREE_PREFERENCE2_MSG')OR define('REQD_SELECT_DEGREE_PREFERENCE2_MSG','Please Choose Degree Preference 2');
defined('REQD_SELECT_DEGREE_PREFERENCE3_MSG')OR define('REQD_SELECT_DEGREE_PREFERENCE3_MSG','Please Choose Degree Preference 3');
defined('REQD_SELECT_SPL_PREFERENCE_MSG')OR define('REQD_SELECT_SPL_PREFERENCE_MSG','Please Choose Specialization Preference
');
defined('REQD_SELECT_CAMPUS_PREFERENCE1_MSG')OR define('REQD_SELECT_CAMPUS_PREFERENCE1_MSG','Please Select Campus Preference 1');
defined('REQD_SELECT_COURSE_PREFERENCE1_MSG')OR define('REQD_SELECT_COURSE_PREFERENCE1_MSG','Please Select Course Preference 1');
defined('REQD_SELECT_CAMPUS_PREFERENCE2_MSG')OR define('REQD_SELECT_CAMPUS_PREFERENCE2_MSG','Please Select Campus Preference 2');
defined('REQD_SELECT_COURSE_PREFERENCE2_MSG')OR define('REQD_SELECT_COURSE_PREFERENCE2_MSG','Please Select Course Preference 2');
defined('REQD_SELECT_CAMPUS_PREFERENCE3_MSG')OR define('REQD_SELECT_CAMPUS_PREFERENCE3_MSG','Please Select Campus Preference 3');
defined('REQD_SELECT_COURSE_PREFERENCE3_MSG')OR define('REQD_SELECT_COURSE_PREFERENCE3_MSG','Please Select Course Preference 3');
defined('REQD_SELECT_STATE_PREFERENCE1_MSG')OR define('REQD_SELECT_STATE_PREFERENCE1_MSG','Select Test State Perferences 1');
defined('REQD_SELECT_CITY_PREFERENCE1_MSG')OR define('REQD_SELECT_CITY_PREFERENCE1_MSG','Please Select Test City Perferences 1');
defined('REQD_SELECT_STATE_PREFERENCE2_MSG')OR define('REQD_SELECT_STATE_PREFERENCE2_MSG','Select Test State Perferences 2');
defined('REQD_SELECT_CITY_PREFERENCE2_MSG')OR define('REQD_SELECT_CITY_PREFERENCE2_MSG','Please Select Test City Perferences 2');
defined('REQD_SELECT_STATE_PREFERENCE3_MSG')OR define('REQD_SELECT_STATE_PREFERENCE3_MSG','Select Test State Perferences 3');
defined('REQD_SELECT_CITY_PREFERENCE3_MSG')OR define('REQD_SELECT_CITY_PREFERENCE3_MSG','Please Select Test City Perferences 3');
defined('REQD_SELECT_SPL_PREFERENCE1_MSG')OR define('REQD_SELECT_SPL_PREFERENCE1_MSG','Please Select Specialization Preference 1');
defined('REQD_SELECT_SPL_PREFERENCE2_MSG')OR define('REQD_SELECT_SPL_PREFERENCE2_MSG','Please Select Specialization Preference 2');
defined('REQD_SELECT_SPL_PREFERENCE3_MSG')OR define('REQD_SELECT_SPL_PREFERENCE3_MSG','Please Select Specialization Preference 3');
defined('REQD_TITLE_MSG')OR define('REQD_TITLE_MSG','Please Select Title');
defined('REQD_FIRST_NAME_MSG')OR define('REQD_FIRST_NAME_MSG','Please Enter First Name');
defined('REQD_ALPHA_NAME_ONLY_MSG')OR define('REQD_ALPHA_NAME_ONLY_MSG','Name must be alphabetic only.');
defined('REQD_ALPHA_ONLY_MSG')OR define('REQD_ALPHA_ONLY_MSG','Please Enter Alphabet Only');
defined('REQD_MIDDLE_NAME_MSG')OR define('REQD_MIDDLE_NAME_MSG','Please Enter Middle Name');
defined('VALID_MIDDLE_NAME_MSG')OR define('VALID_MIDDLE_NAME_MSG','Please Enter Valid Middle Name');
defined('REQD_LAST_NAME_MSG')OR define('REQD_LAST_NAME_MSG','Please Enter Last Name');
defined('REQD_MOBILE_MSG')OR define('REQD_MOBILE_MSG','Please Enter Mobile Number');
defined('VALID_MOBILE_MSG')OR define('VALID_MOBILE_MSG','Please Enter Valid Mobile Number');
defined('REQD_EMAIL_MSG')OR define('REQD_EMAIL_MSG','Please Enter Email ID');
defined('VALID_EMAIL_MSG')OR define('VALID_EMAIL_MSG','Please Enter Valid Email ID');
defined('REQD_DOB_MSG')OR define('REQD_DOB_MSG','Please Pick Date of Birth');
defined('REQD_GENDER_MSG')OR define('REQD_GENDER_MSG','Please Select Gender');
defined('VALID_ALT_EMAIL_MSG')OR define('VALID_ALT_EMAIL_MSG','Please Enter Valid Alternate Email ID');
defined('REQD_BLOOD_GRP_MSG')OR define('REQD_BLOOD_GRP_MSG','Please Select Blood Group');
defined('REQD_AADHAR_NO_MSG')OR define('REQD_AADHAR_NO_MSG','Please Enter Aadhar Number');
defined('VALID_AADHAR_NO_MSG')OR define('VALID_AADHAR_NO_MSG','Please Enter Valid Aadhar Number');
defined('REQD_RELIGION_MSG')OR define('REQD_RELIGION_MSG','Please Select Religion');
defined('REQD_MOTHER_TONGUE_MSG')OR define('REQD_MOTHER_TONGUE_MSG','Please Select Mother Tongue');
defined('REQD_MEDIUM_INSTR_MSG')OR define('REQD_MEDIUM_INSTR_MSG','Please Select Medium of Instruction');
defined('REQD_HOSTEL_ACCOM_MSG')OR define('REQD_HOSTEL_ACCOM_MSG','Please Select Hostel Accommodation');
defined('REQD_DIFF_ABLED_MSG')OR define('REQD_DIFF_ABLED_MSG','Please Select Differently Abled Status');
defined('REQD_ADVERTISE_MSG')OR define('REQD_ADVERTISE_MSG','Please Select Advertisement Source');
defined('REQD_NATION_MSG')OR define('REQD_NATION_MSG','Please Select Nationality');
defined('REQD_SELECT_RELATION_APLCT_MSG')OR define('REQD_SELECT_RELATION_APLCT_MSG','Please Choose Relationship Applicant');
defined('REQD_SOCIAL_STATUS_MSG')OR define('REQD_SOCIAL_STATUS_MSG','Please Select Social Status');
defined('REQD_COMMUNITY_MSG')OR define('REQD_COMMUNITY_MSG','Please Select Community');
defined('REQD_FATHER_NAME_MSG')OR define('REQD_FATHER_NAME_MSG','Please Enter Your Father Name');
defined('REQD_FATHER_ALT_MOBILE_MSG')OR define('REQD_FATHER_ALT_MOBILE_MSG','Please Enter father Alternative Mobile Number');
defined('REQD_FATHER_MOBILE_MSG')OR define('REQD_FATHER_MOBILE_MSG','Please Enter Mobile Number');
defined('VALID_FATHER_MOBILE_MSG')OR define('VALID_FATHER_MOBILE_MSG','Please Enter Valid Mobile Number');
defined('REQD_FATHER_EMAIL_MSG')OR define('REQD_FATHER_EMAIL_MSG','Please Enter Email ID');
defined('VALID_FATHER_EMAIL_MSG')OR define('VALID_FATHER_EMAIL_MSG','Please Enter Valid Email ID');
defined('REQD_FATHER_OTHER_OCCUPATION_MSG')OR define('REQD_FATHER_OTHER_OCCUPATION_MSG','Please Enter Other Occupation');
defined('REQD_MSG')OR define('REQD_MSG','Required');
defined('REQD_MOTHER_NAME_MSG')OR define('REQD_MOTHER_NAME_MSG','Please Enter Your Mother Name');
defined('REQD_MOTHER_MOBILE_MSG')OR define('REQD_MOTHER_MOBILE_MSG','Please Enter Mobile Number');
defined('VALID_MOTHER_MOBILE_MSG')OR define('VALID_MOTHER_MOBILE_MSG','Please Enter Valid Mobile Number');
defined('REQD_MOTHER_EMAIL_MSG')OR define('REQD_MOTHER_EMAIL_MSG','Please Enter Email ID');
defined('VALID_MOTHER_EMAIL_MSG')OR define('VALID_MOTHER_EMAIL_MSG','Please Enter Valid Email ID');
defined('REQD_MOTHER_OTHER_OCCUPATION_MSG')OR define('REQD_MOTHER_OTHER_OCCUPATION_MSG','Please Enter Other Occupation');
defined('REQD_GUARDIAN_NAME_MSG')OR define('REQD_GUARDIAN_NAME_MSG','Please Enter Your Guardian Name');
defined('REQD_GUARDIAN_MOBILE_MSG')OR define('REQD_GUARDIAN_MOBILE_MSG','Please Enter Your Guardian Mobile Number');
defined('REQD_GUARDIAN_EMAIL_MSG')OR define('REQD_GUARDIAN_EMAIL_MSG','Please Enter Your Guardian Email ID');
defined('VALID_GUARDIAN_MOBILE_MSG')OR define('VALID_GUARDIAN_MOBILE_MSG','Please Enter Valid Guardian Mobile Number');
defined('VALID_GUARDIAN_EMAIL_MSG')OR define('VALID_GUARDIAN_EMAIL_MSG','Please Enter Valid Guardian Email ID');
defined('REQD_GUARDIAN_OCCUPATION_MSG')OR define('REQD_GUARDIAN_OCCUPATION_MSG','Select Guardian Occupation');
defined('REQD_GUARDIAN_OTHER_OCCUPATION_MSG')OR define('REQD_GUARDIAN_OTHER_OCCUPATION_MSG','Please Enter Other Occupation');
defined('REQD_COUNTRY_MSG')OR define('REQD_COUNTRY_MSG','Please Select Country');
defined('REQD_STATE_MSG')OR define('REQD_STATE_MSG','Please Select State');
defined('REQD_DISTRICT_MSG')OR define('REQD_DISTRICT_MSG','Please Select District');
defined('REQD_CITY_MSG')OR define('REQD_CITY_MSG','Please Select City');
defined('REQD_ADDRESS_MSG')OR define('REQD_ADDRESS_MSG','Please Enter Address');
defined('REQD_PINCODE_MSG')OR define('REQD_PINCODE_MSG','Please Enter Pincode');
defined('VALID_PINCODE_MSG')OR define('VALID_PINCODE_MSG','Please Enter Valid Pincode');
defined('REQD_QUALIFY_EXAM_NAME_MSG')OR define('REQD_QUALIFY_EXAM_NAME_MSG','Please Enter Qualifying Exam Name');
defined('REQD_DEGREE_NAME_MSG')OR define('REQD_DEGREE_NAME_MSG','Please Enter Degree Name');
defined('REQD_INSTITUTE_UNIV_MSG')OR define('REQD_INSTITUTE_UNIV_MSG','Please Select Institute / University');
defined('REQD_MAJOR_DISCIPLINE_MSG')OR define('REQD_MAJOR_DISCIPLINE_MSG','Please Enter Major Discipline');
defined('ALPHA_MAJOR_DISCIPLINE_MSG')OR define('ALPHA_MAJOR_DISCIPLINE_MSG','Major discipline must be alphabetic only.');
defined('REQD_EDU_QUAL_MSG')OR define('REQD_EDU_QUAL_MSG','Please Select Current Education Qualification Status');
defined('REQD_CANDIDATE_NAME_MSG')OR define('REQD_CANDIDATE_NAME_MSG','Please Enter Candidate\'s Name');
defined('REQD_CUR_HIGH_EDU_MSG')OR define('REQD_CUR_HIGH_EDU_MSG','Please Select Current Highest Education');
defined('REQD_DECLARE_MONTH_MSG')OR define('REQD_DECLARE_MONTH_MSG','Please Select declare Month and Year');
defined('REQD_INSTITUTE_NAME_MSG')OR define('REQD_INSTITUTE_NAME_MSG','Please Enter Institute Name');
defined('REQD_BOARD_MSG')OR define('REQD_BOARD_MSG','Please Select Board');
defined('REQD_OTHER_BOARD_MSG')OR define('REQD_OTHER_BOARD_MSG','Please Enter Other Board');
defined('REQD_BOARD_AREA_MSG')OR define('REQD_BOARD_AREA_MSG','Please Enter Board Area');
defined('REQD_UNIVERSITY_MSG')OR define('REQD_UNIVERSITY_MSG','Please Select University');
defined('REQD_OTHER_UNIVERSITY_MSG')OR define('REQD_OTHER_UNIVERSITY_MSG','Please Enter Other University');
defined('REQD_LANG_PREFERENCE_MSG')OR define('REQD_LANG_PREFERENCE_MSG','Select Language preference');
defined('REQD_LEARNER_CENTER_MSG')OR define('REQD_LEARNER_CENTER_MSG','Please Learner Support Centers');
defined('REQD_STREAM_MSG')OR define('REQD_STREAM_MSG','Please Select Stream');
defined('REQD_OTHER_STREAM_MSG')OR define('REQD_OTHER_STREAM_MSG','Please Enter Other Stream');
defined('REQD_REG_NO_MSG')OR define('REQD_REG_NO_MSG','Please Enter Roll No. / Registration No');
defined('VALID_REG_NO_MSG')OR define('VALID_REG_NO_MSG','Enter Valid Roll / Registration Number');
defined('REQD_MODE_STUDY_MSG')OR define('REQD_MODE_STUDY_MSG','Please Select Mode of Study');
defined('REQD_YEAR_OF_PASSING_MSG')OR define('REQD_YEAR_OF_PASSING_MSG','Please Enter Year of Passing');
defined('REQD_MARK_SCHEME_MSG')OR define('REQD_MARK_SCHEME_MSG','Please Select Marking Scheme');
defined('REQD_PERCENT_CGPA_MSG')OR define('REQD_PERCENT_CGPA_MSG','Please Enter Percentage/CGPA');
defined('REQD_PERCENT_CGPA_VALID_MSG')OR define('REQD_PERCENT_CGPA_VALID_MSG','Please Enter Valid Percentage/CGPA');
defined('VALID_PERCENT_CGPA_MSG')OR define('VALID_PERCENT_CGPA_MSG','Please Enter Valid CGPA');
defined('REQD_SCHOOL_ADDRESS_MSG')OR define('REQD_SCHOOL_ADDRESS_MSG','Please Enter Address of School / College');
defined('REQD_NADID_MSG')OR define('REQD_NADID_MSG','Enter NAD ID / Digilocker ID');
defined('VALID_NADID_MSG')OR define('VALID_NADID_MSG','Enter Valid NAD ID / Digilocker ID');
defined('REQD_COMP_STATUS_MSG')OR define('REQD_COMP_STATUS_MSG','Please Select Status');
defined('REQD_COMP_EXAM_MSG')OR define('REQD_COMP_EXAM_MSG','Please select Competitive Examination');
defined('REQD_COMP_REGNO_MSG')OR define('REQD_COMP_REGNO_MSG','Please Enter Registration No');
defined('REQD_SCORE_MSG')OR define('REQD_SCORE_MSG','Please Enter Score Obtained');
defined('VALID_SCORE_MSG')OR define('VALID_SCORE_MSG','Please Enter Valid Score Obtained');
defined('REQD_MAX_SCORE_MSG')OR define('REQD_MAX_SCORE_MSG','Please Enter Max Score');
defined('VALID_MAX_SCORE_MSG')OR define('VALID_MAX_SCORE_MSG','Please Enter Valid Max Score');
defined('REQD_YEAR_APPEAR_MSG')OR define('REQD_YEAR_APPEAR_MSG','Please Enter Year Appeared');
defined('REQD_AIR_RANK_MSG')OR define('REQD_AIR_RANK_MSG','Please Enter AIR / Overall Rank');
defined('VALID_AIR_RANK_MSG')OR define('VALID_AIR_RANK_MSG','Please Enter Valid AIR / Overall Rank');
defined('REQD_QUALIFY_STATUS_MSG')OR define('REQD_QUALIFY_STATUS_MSG','Please Select Qualified / Not Qualified');
defined('REQD_WORK_EXP_MSG')OR define('REQD_WORK_EXP_MSG','Please Select Work Experience');
defined('REQD_ORG_NAME_MSG')OR define('REQD_ORG_NAME_MSG','Please Enter Organisation Name');
defined('REQD_DESIGNATION_MSG')OR define('REQD_DESIGNATION_MSG','Please Enter Designation');
defined('REQD_SECTOR_MSG')OR define('REQD_SECTOR_MSG','Please Select Sector');
defined('REQD_NATURE_MSG')OR define('REQD_NATURE_MSG','Please Enter Nature Of Job');
defined('REQD_TOT_SALARY_MSG')OR define('REQD_TOT_SALARY_MSG','Please Enter Total Salary');
defined('REQD_FROM_YEAR_MSG')OR define('REQD_FROM_YEAR_MSG','Please Enter From Year');
defined('REQD_TO_YEAR_MSG')OR define('REQD_TO_YEAR_MSG','Please Enter To Year');
defined('REQD_PAYMENT_MODE_MSG')OR define('REQD_PAYMENT_MODE_MSG','Please Choose Payment Mode');
defined('REQD_CHOOSE_BANK_MSG')OR define('REQD_CHOOSE_BANK_MSG','Please Choose Bank Name');
defined('REQD_BANK_NAME_MSG')OR define('REQD_BANK_NAME_MSG','Please Enter Branch Name');
defined('VALID_BANK_NAME_MSG')OR define('VALID_BANK_NAME_MSG','Please Enter Valid Branch Name');
defined('REQD_DD_NO_MSG')OR define('REQD_DD_NO_MSG','Please Enter DD Number');
defined('VALID_DD_NO_MSG')OR define('VALID_DD_NO_MSG','Only Numbers Allowed');
defined('REQD_DD_DATE_MSG')OR define('REQD_DD_DATE_MSG','Please Enter DD Date');
defined('DD_INFAVOUR')OR define('DD_INFAVOUR','You must send your DD&nbsp;in favor of "SRMIST" Payable at Chennai. along with your Application Form with complete details (Full Name, Application Number, Mobile) to &nbsp;the below-mentioned address:<br><br>The Director (Admissions)<br>SRM Institute of Science and technology<br>SRM Nagar,<br>Kattankulathur-603 203<br>Chengalpattu District<br>Tamil Nadu, India');
defined('REQD_UPLOAD_PHOTO_MSG')OR define('REQD_UPLOAD_PHOTO_MSG','Please Upload Photograph');
defined('REQD_UPLOAD_SIGN_MSG')OR define('REQD_UPLOAD_SIGN_MSG','Please Upload Signature');
defined('REQD_UPLOAD_OTHER_DOC1_MSG')OR define('REQD_UPLOAD_OTHER_DOC1_MSG','Please Upload Any Other Document 1');
defined('REQD_UPLOAD_OTHER_DOC2_MSG')OR define('REQD_UPLOAD_OTHER_DOC2_MSG','Please Upload Any Other Document 2');
defined('REQD_UPLOAD_10_MARKSHEET_MSG')OR define('REQD_UPLOAD_10_MARKSHEET_MSG','Please Upload 10th Marksheet');
defined('REQD_UPLOAD_10_GRADE_MSG')OR define('REQD_UPLOAD_10_GRADE_MSG','Please Upload 10th Grade Marksheet');
defined('REQD_UPLOAD_12_MARKSHEET_MSG')OR define('REQD_UPLOAD_12_MARKSHEET_MSG','Please Upload 12th Marksheet');
defined('REQD_UPLOAD_12_GRADE_MSG')OR define('REQD_UPLOAD_12_GRADE_MSG','Please Upload 12th Grade Marksheet');
defined('REQD_UPLOAD_BACHELOR_MARK_MSG')OR define('REQD_UPLOAD_BACHELOR_MARK_MSG','Please Upload Bachelors Marksheet');defined('REQD_UPLOAD_MASTER_MARK_MSG')OR define('REQD_UPLOAD_MASTER_MARK_MSG','Please Upload Masters Marks Card');
defined('REQD_UPLOAD_TRANSCRIPT_MSG')OR define('REQD_UPLOAD_TRANSCRIPT_MSG','Please Upload Transcripts');
defined('REQD_UPLOAD_PROV_CERTIFY_MSG')OR define('REQD_UPLOAD_PROV_CERTIFY_MSG','Please Upload Provisional Certificate');
defined('REQD_UPLOAD_AADHAR_CARD_MSG')OR define('REQD_UPLOAD_AADHAR_CARD_MSG','Please Upload Your Aadhar Card');
defined('REQD_UPLOAD_GRAD_MARK_MSG')OR define('REQD_UPLOAD_GRAD_MARK_MSG','Please Upload Graduation Marksheet');
defined('REQD_UPLOAD_PG_GRAD_MARK_MSG')OR define('REQD_UPLOAD_PG_GRAD_MARK_MSG','Please Upload Post Graduation Marksheet');
defined('REQD_UPLOAD_ADD_QUALIFY_MSG')OR define('REQD_UPLOAD_ADD_QUALIFY_MSG','Please Upload Additional Qualification');
defined('REQD_UPLOAD_COMP_EXAM_MSG')OR define('REQD_UPLOAD_COMP_EXAM_MSG','Please Upload Your Competitive Exam Marksheet');
defined('DECLARATION')OR define('DECLARATION','I certify that the information submitted by me in support of this application, is true to the best of my knowledge and belief. I understand that in the event of any information being found false or incorrect, my admission is liable to be rejected / cancelled at any stage of the program. I undertake to abide by the disciplinary rules and regulations of the institute');
defined('REQD_APPLT_NAME_MSG')OR define('REQD_APPLT_NAME_MSG','Please Enter Applicant Name');
defined('REQD_PARENT_NAME_MSG')OR define('REQD_PARENT_NAME_MSG','Please Enter Parent Name');
defined('REQD_QUALIFY_DEGREE_MSG')OR define('REQD_QUALIFY_DEGREE_MSG','Please Choose Qualifying Degree');
defined('REQD_QUALIFY_DEGREE_OTHER_MSG')OR define('REQD_QUALIFY_DEGREE_OTHER_MSG','Please Enter Other Qualifying Degree');
defined('REQD_SPL_QUALIFY_DEGREE_OTHER_MSG')OR define('REQD_SPL_QUALIFY_DEGREE_OTHER_MSG','Please Enter Other Specialization Qualifying Degree');
defined('REQD_SPL_QUALIFY_DEGREE_MSG')OR define('REQD_SPL_QUALIFY_DEGREE_MSG','Please Choose Specialization In Qualifying Degree');
defined('REQD_DEP_SCH_COL_MSG')OR define('REQD_DEP_SCH_COL_MSG','Please Choose Department / School / College');
defined('REQD_OTHER_DEP_SCH_COL_MSG')OR define('REQD_OTHER_DEP_SCH_COL_MSG','Please Enter Other Department');
defined('REQD_FACULTY_OTHER_MSG')OR define('REQD_FACULTY_OTHER_MSG','Please Enter Other Faculty');
defined('REQD_ARE_YOU_EMPLOYED')OR define('REQD_ARE_YOU_EMPLOYED','Please Choose Are you Employed ?');
defined('REQD_WORKING_PLACE')OR define('REQD_WORKING_PLACE','Please Choose Working Place');
defined('REQD_OTHER_WORKING_PLACE')OR define('REQD_OTHER_WORKING_PLACE','Please Enter Other Working Place');
defined('REQD_FACULTY_MSG')OR define('REQD_FACULTY_MSG','Please Choose Faculty');
defined('REQD_CATEGORY_MSG')OR define('REQD_CATEGORY_MSG','Please Choose Category');
defined('REQD_PHD_TITLE_MSG')OR define('REQD_PHD_TITLE_MSG','Please Choose Title');
defined('REQD_NATURE_DEFORMITY_MSG')OR define('REQD_NATURE_DEFORMITY_MSG','Please Choose Nature of Deformity');
defined('REQD_PERCENT_NATURE_DEFORMITY_MSG')OR define('REQD_PERCENT_NATURE_DEFORMITY_MSG','Please Choose Percentage of Deformity');
defined('REQD_PG_MARK_MSG')OR define('REQD_PG_MARK_MSG','Please Upload Post Graduation Marksheet');
defined('REQD_UPLOAD_SCORE_CARD_MSG')OR define('REQD_UPLOAD_SCORE_CARD_MSG','Please Upload Score Card');
defined('REQD_EMP_NAME_MSG')OR define('REQD_EMP_NAME_MSG','Please Enter Name of Employee');
defined('REQD_EMP_ADDRESS_MSG')OR define('REQD_EMP_ADDRESS_MSG','Please Enter Address of Employee');
defined('REQD_SALARY_PER_MONTH_MSG')OR define('REQD_SALARY_PER_MONTH_MSG','Please Enter Salary Per Month');
defined('VALID_DIGITS_ONLY_MSG')OR define('VALID_DIGITS_ONLY_MSG','Only Numbers Allowed');
defined('VALID_ALPHA_ONLY_MSG')OR define('VALID_ALPHA_ONLY_MSG','Only Alphabetic Allowed');
defined('REQD_NATURE_JOB_MSG')OR define('REQD_NATURE_JOB_MSG','Please Enter Nature of Job');
defined('REQD_TOTAL_SALARY_MONTH_MSG')OR define('REQD_TOTAL_SALARY_MONTH_MSG','Please Enter Total Salary Month');
defined('REQD_TENTATIVE_TOPIC_MSG')OR define('REQD_TENTATIVE_TOPIC_MSG','Please Upload Tentative Topic');
defined('REQD_CHOICE_SUPERVISOR_MSG')OR define('REQD_CHOICE_SUPERVISOR_MSG','Please Enter Choice of Supervisor');
defined('REQD_DESIGN_ALPHA_MSG')OR define('REQD_DESIGN_ALPHA_MSG','Designation must be alphabetic only.');
defined('REQD_NATURE_ALPHA_MSG')OR define('REQD_NATURE_ALPHA_MSG','Nature of Job must be alphabetic only.');
defined('REQD_PUBLICATION_ALPHA_MSG')OR define('REQD_PUBLICATION_ALPHA_MSG','Publication Title must be alphabetic only.');defined('REQD_JOURNAL_ALPHA_MSG')OR define('REQD_JOURNAL_ALPHA_MSG','Name of Journal must be alphabetic only.');
defined('REQD_JOB_NATURE_MSG')OR define('REQD_JOB_NATURE_MSG','Please Enter Nature of Responsibilities');
defined('REQD_EMPLOYED_MSG')OR define('REQD_EMPLOYED_MSG','Please Select Employed Status');
defined('REQD_CHOOSE_RESIDENT_MSG')OR define('REQD_CHOOSE_RESIDENT_MSG','Please Choose Resident');
defined('REQD_CHOOSE_PROGRAM_MSG')OR define('REQD_CHOOSE_PROGRAM_MSG','Please Choose Program');
defined('REQD_CHOOSE_COURSE_MSG')OR define('REQD_CHOOSE_COURSE_MSG','Please Choose Course');
defined('REQD_CHOOSE_CAMPUS_MSG')OR define('REQD_CHOOSE_CAMPUS_MSG','Please Choose Campus');
defined('REQD_SCHOOL_NAME_MSG')OR define('REQD_SCHOOL_NAME_MSG','Please Enter School Name');
defined('REQD_SELECT_EXAM_MSG')OR define('REQD_SELECT_EXAM_MSG','Please Choose Examination');
defined('REQD_SELECT_SUBJECT_MSG')OR define('REQD_SELECT_SUBJECT_MSG','Please Choose Subject');
/* Form Field Validation message end here */

/* Form Field min & max length */
defined('APLCT_1_MAXLENGTH')OR define('APLCT_1_MAXLENGTH',1);
defined('APLCT_100_MAXLENGTH')OR define('APLCT_100_MAXLENGTH',100);
defined('APLCT_SPONSER_MINLENGTH')OR define('APLCT_SPONSER_MINLENGTH',1);
defined('APLCT_SPONSER_MAXLENGTH')OR define('APLCT_SPONSER_MAXLENGTH',100);
defined('APLCT_OTHER_BOARD_MAXLENGTH')OR define('APLCT_OTHER_BOARD_MAXLENGTH',100);
defined('APLCT_FIRST_NAME_MINLENGTH')OR define('APLCT_FIRST_NAME_MINLENGTH',1);
defined('APLCT_FIRST_NAME_MAXLENGTH')OR define('APLCT_FIRST_NAME_MAXLENGTH',100);
defined('APLCT_MIDDLE_NAME_MINLENGTH')OR define('APLCT_MIDDLE_NAME_MINLENGTH',1);
defined('APLCT_MIDDLE_NAME_MAXLENGTH')OR define('APLCT_MIDDLE_NAME_MAXLENGTH',50);
defined('APLCT_LAST_NAME_MINLENGTH')OR define('APLCT_LAST_NAME_MINLENGTH',1);
defined('APLCT_LAST_NAME_MAXLENGTH')OR define('APLCT_LAST_NAME_MAXLENGTH',50);
defined('APLCT_MOBILE_MAXLENGTH')OR define('APLCT_MOBILE_MAXLENGTH',10);
defined('APLCT_EMAIL_MAXLENGTH')OR define('APLCT_EMAIL_MAXLENGTH',100);
defined('APLCT_ALT_EMAIL_MAXLENGTH')OR define('APLCT_ALT_EMAIL_MAXLENGTH',100);
defined('APLCT_AADHAR_MINLENGTH')OR define('APLCT_AADHAR_MINLENGTH',12);
defined('APLCT_AADHAR_MAXLENGTH')OR define('APLCT_AADHAR_MAXLENGTH',12);
defined('APLCT_FATHER_NAME_MINLENGTH')OR define('APLCT_FATHER_NAME_MINLENGTH',1);
defined('APLCT_FATHER_NAME_MAXLENGTH')OR define('APLCT_FATHER_NAME_MAXLENGTH',50);
defined('APLCT_FATHER_MOBILE_MAXLENGTH')OR define('APLCT_FATHER_MOBILE_MAXLENGTH',10);
defined('APLCT_FATHER_ALT_MOBILE_MAXLENGTH')OR define('APLCT_FATHER_ALT_MOBILE_MAXLENGTH',10);
defined('APLCT_FATHER_EMAIL_MAXLENGTH')OR define('APLCT_FATHER_EMAIL_MAXLENGTH',100);
defined('APLCT_FATHER_OCCP_MAXLENGTH')OR define('APLCT_FATHER_OCCP_MAXLENGTH',50);
defined('APLCT_MOTHER_NAME_MINLENGTH')OR define('APLCT_MOTHER_NAME_MINLENGTH',1);
defined('APLCT_MOTHER_NAME_MAXLENGTH')OR define('APLCT_MOTHER_NAME_MAXLENGTH',50);
defined('APLCT_MOTHER_MOBILE_MAXLENGTH')OR define('APLCT_MOTHER_MOBILE_MAXLENGTH',10);
defined('APLCT_MOTHER_ALT_MOBILE_MAXLENGTH')OR define('APLCT_MOTHER_ALT_MOBILE_MAXLENGTH',10);
defined('APLCT_MOTHER_EMAIL_MAXLENGTH')OR define('APLCT_MOTHER_EMAIL_MAXLENGTH',100);
defined('APLCT_MOTHER_OCCP_MAXLENGTH')OR define('APLCT_MOTHER_OCCP_MAXLENGTH',50);
defined('APLCT_GUARDIAN_NAME_MINLENGTH')OR define('APLCT_GUARDIAN_NAME_MINLENGTH',1);
defined('APLCT_GUARDIAN_NAME_MAXLENGTH')OR define('APLCT_GUARDIAN_NAME_MAXLENGTH',50);
defined('APLCT_GUARDIAN_MOBILE_MAXLENGTH')OR define('APLCT_GUARDIAN_MOBILE_MAXLENGTH',10);
defined('APLCT_GUARDIAN_EMAIL_MAXLENGTH')OR define('APLCT_GUARDIAN_EMAIL_MAXLENGTH',100);
defined('APLCT_GUARDIAN_OCCP_MAXLENGTH')OR define('APLCT_GUARDIAN_OCCP_MAXLENGTH',50);
defined('APLCT_ADDRESS1_MAXLENGTH')OR define('APLCT_ADDRESS1_MAXLENGTH',100);
defined('APLCT_ADDRESS2_MAXLENGTH')OR define('APLCT_ADDRESS2_MAXLENGTH',100);
defined('APLCT_PINCODE_MINLENGTH')OR define('APLCT_PINCODE_MINLENGTH',6);
defined('APLCT_PINCODE_MAXLENGTH')OR define('APLCT_PINCODE_MAXLENGTH',6);
defined('APLCT_DEGREE_MAXLENGTH')OR define('APLCT_DEGREE_MAXLENGTH',50);
defined('APLCT_CAND_NAME_MINLENGTH')OR define('APLCT_CAND_NAME_MINLENGTH',1);
defined('APLCT_CAND_NAME_MAXLENGTH')OR define('APLCT_CAND_NAME_MAXLENGTH',100);
defined('APLCT_INSTITUTE_NAME_MINLENGTH')OR define('APLCT_INSTITUTE_NAME_MINLENGTH',1);
defined('APLCT_INSTITUTE_NAME_MAXLENGTH')OR define('APLCT_INSTITUTE_NAME_MAXLENGTH',100);
defined('APLCT_SCHOOL_ADDRESS_MAXLENGTH')OR define('APLCT_SCHOOL_ADDRESS_MAXLENGTH',100);
defined('APLCT_OTHER_UG_MAXLENGTH')OR define('APLCT_OTHER_UG_MAXLENGTH',100);
defined('APLCT_OTHER_GRAD_MAXLENGTH')OR define('APLCT_OTHER_GRAD_MAXLENGTH',200);
defined('APLCT_REG_NO_MINLENGTH')OR define('APLCT_REG_NO_MINLENGTH',1);
defined('APLCT_REG_NO_MAXLENGTH')OR define('APLCT_REG_NO_MAXLENGTH',20);
defined('APLCT_YEAR_OF_PASSING_MAXLENGTH')OR define('APLCT_YEAR_OF_PASSING_MAXLENGTH',4);
defined('APLCT_YEAR_APPEAR_MAXLENGTH')OR define('APLCT_YEAR_APPEAR_MAXLENGTH',4);
defined('APLCT_PERCENT_CGPA_MAXLENGTH')OR define('APLCT_PERCENT_CGPA_MAXLENGTH',5);
defined('APLCT_MAJOR_DISPLICINE_MAXLENGTH')OR define('APLCT_MAJOR_DISPLICINE_MAXLENGTH',50);
defined('APLCT_MARK_MINLENGTH')OR define('APLCT_MARK_MINLENGTH',33);
defined('APLCT_MARK_MAXLENGTH')OR define('APLCT_MARK_MAXLENGTH',100);
defined('APLCT_NADID_MAXLENGTH')OR define('APLCT_NADID_MAXLENGTH',12);
defined('APLCT_SCORE_MAXLENGTH')OR define('APLCT_SCORE_MAXLENGTH',5);
defined('APLCT_MAX_SCORE_MAXLENGTH')OR define('APLCT_MAX_SCORE_MAXLENGTH',4);
defined('APLCT_OVERALL_RANK_MAXLENGTH')OR define('APLCT_OVERALL_RANK_MAXLENGTH',4);
defined('APLCT_ORGANISATION_NAME_MAXLENGTH')OR define('APLCT_ORGANISATION_NAME_MAXLENGTH',100);
defined('APLCT_DESIGNATION_MAXLENGTH')OR define('APLCT_DESIGNATION_MAXLENGTH',100);
defined('APLCT_OTHER_SECTOR_MAXLENGTH')OR define('APLCT_OTHER_SECTOR_MAXLENGTH',100);
defined('APLCT_SALARY_PACKAGE_MAXLENGTH')OR define('APLCT_SALARY_PACKAGE_MAXLENGTH',4);
defined('APLCT_WORK_EXP_MINLENGTH')OR define('APLCT_WORK_EXP_MINLENGTH',1);
defined('APLCT_WORK_EXP_MAXLENGTH')OR define('APLCT_WORK_EXP_MAXLENGTH',4);
defined('APLCT_TOT_WORK_EXP_MAXLENGTH')OR define('APLCT_TOT_WORK_EXP_MAXLENGTH',5);
defined('APLCT_BRANCH_NAME_MAXLENGTH')OR define('APLCT_BRANCH_NAME_MAXLENGTH',30);
defined('APLCT_DD_NO_MAXLENGTH')OR define('APLCT_DD_NO_MAXLENGTH',15);
defined('APLCT_DECLR_NAME_MINLENGTH')OR define('APLCT_DECLR_NAME_MINLENGTH',1);
defined('APLCT_DECLR_NAME_MAXLENGTH')OR define('APLCT_DECLR_NAME_MAXLENGTH',100);
defined('APLCT_DECLR_FATHER_NAME_MINLENGTH')OR define('APLCT_DECLR_FATHER_NAME_MINLENGTH',1);
defined('APLCT_DECLR_FATHER_NAME_MAXLENGTH')OR define('APLCT_DECLR_FATHER_NAME_MAXLENGTH',100);
defined('APLCT_OTHER_STREAM_MAXLENGTH')OR define('APLCT_OTHER_STREAM_MAXLENGTH',100);

defined('APLCT_JOB_NATURE_MAXLENGTH')OR define('APLCT_JOB_NATURE_MAXLENGTH',50);
defined('TYPE_NA')OR define('TYPE_NA','Kindly type \'NA\' in case Certificate is not available with you.');
defined('TYPE_NA_NOT_AVAIL')OR define('TYPE_NA_NOT_AVAIL','Kindly type \'NA\' if details is not available');
defined('APLCT_EMPLOYEE_NAME_MAXLENGTH')OR define('APLCT_EMPLOYEE_NAME_MAXLENGTH',150);
defined('APLCT_EMPLOYEE_ADDRESS_MAXLENGTH')OR define('APLCT_EMPLOYEE_ADDRESS_MAXLENGTH',500);
defined('APLCT_SALARY_PER_MONTH_MAXLENGTH')OR define('APLCT_SALARY_PER_MONTH_MAXLENGTH',10);
defined('APLCT_FROM_YEAR_MAXLENGTH')OR define('APLCT_FROM_YEAR_MAXLENGTH',7);
defined('APLCT_TO_YEAR_MAXLENGTH')OR define('APLCT_TO_YEAR_MAXLENGTH',7);
defined('APLCT_PUBLICATION_TITLE_MAXLENGTH')OR define('APLCT_PUBLICATION_TITLE_MAXLENGTH',100);
defined('APLCT_PUBLICATION_JOURNAL_MAXLENGTH')OR define('APLCT_PUBLICATION_JOURNAL_MAXLENGTH',100);
defined('APLCT_PUBLICATION_YEAR_MAXLENGTH')OR define('APLCT_PUBLICATION_YEAR_MAXLENGTH',4);
defined('APLCT_MAJOR_AREA_MAXLENGTH')OR define('APLCT_MAJOR_AREA_MAXLENGTH',100);
defined('APLCT_TENTATIVE_TOPIC_MAXLENGTH')OR define('APLCT_TENTATIVE_TOPIC_MAXLENGTH',100);
defined('APLCT_SUPERVISOR_MAXLENGTH')OR define('APLCT_SUPERVISOR_MAXLENGTH',1000);
defined('APLCT_BOARD_AREA_MAXLENGTH')OR define('APLCT_BOARD_AREA_MAXLENGTH',80);
defined('APLCT_PROPOSED_SUPERVISOR_MAXLENGTH')OR define('APLCT_PROPOSED_SUPERVISOR_MAXLENGTH',100);
defined('FATHER_EMAIL_MAXLENGTH')OR define('FATHER_EMAIL_MAXLENGTH',100);
defined('MOTHER_EMAIL_MAXLENGTH')OR define('MOTHER_EMAIL_MAXLENGTH',100);
/** alerts**/
defined('NO_OPTION_PROCEED_MSG')OR define('NO_OPTION_PROCEED_MSG','Cannot Proceed. Please read instruction below');

/**** A2557 Select Dropdown On Search No Data Message A2557 ****/
defined('NO_EWS_MSG')OR define('NO_EWS_MSG','Sorry, Economically Weaker Section not available.');
defined('NO_WORKING_DSC_MSG')OR define('NO_WORKING_DSC_MSG','Sorry, Working not available.');
defined('NO_FACULTY_MSG')OR define('NO_FACULTY_MSG','Sorry, Faculty not available.');
defined('NO_WE_MSG')OR define('NO_WE_MSG','Sorry, Work Experience not available.');
defined('NO_IU_MSG')OR define('NO_IU_MSG','Sorry, Institute / Univeristy not available.');
defined('NO_CATEGORY_MSG')OR define('NO_CATEGORY_MSG','Sorry, Category not available.');
defined('NO_STUDY_RESIDENT_IN_MSG')OR define('NO_STUDY_RESIDENT_IN_MSG','Sorry, Studied Resident not available.');
defined('NO_RESIDENT_STATUS_MSG')OR define('NO_RESIDENT_STATUS_MSG','Sorry,  Resident status/category not available.');
defined('NO_GENDER_TITLE_MSG')OR define('NO_GENDER_TITLE_MSG','Sorry, Gender Title not available.');
defined('NO_GENDER_MSG')OR define('NO_GENDER_MSG','Sorry, Gender not available.');
defined('NO_MOBILE_CODE_MSG')OR define('NO_MOBILE_CODE_MSG','Sorry, Mobile Code not available.');
defined('NO_BLOOD_GROUP_MSG')OR define('NO_BLOOD_GROUP_MSG','Sorry, Blood Group not available.');
defined('NO_RELIGIONS_MSG')OR define('NO_RELIGIONS_MSG','Sorry, Religion not available.');
defined('NO_MOTHER_TONGUES_MSG')OR define('NO_MOTHER_TONGUES_MSG','Sorry, Mother Tongue not available.');
defined('NO_MEDIUM_OF_INSTRUCTION_MSG')OR define('NO_MEDIUM_OF_INSTRUCTION_MSG','Sorry, Medium Of Instruction not available.');
defined('NO_HOSTEL_ACCOMMODATION_MSG')OR define('NO_HOSTEL_ACCOMMODATION_MSG','Sorry, Hostel Accommodation not available.');
defined('NO_DIFFRENTLY_ABLED_MSG')OR define('NO_DIFFRENTLY_ABLED_MSG','Sorry, Differently Abled not available.');
defined('NO_ADVERTISEMENT_SOURCE_MSG')OR define('NO_ADVERTISEMENT_SOURCE_MSG','Sorry, Advertisement Source not available.');
defined('NO_NATIONALITY_MSG')OR define('NO_NATIONALITY_MSG','Sorry, Nationality not available.');
defined('NO_SOCIAL_STATUS_MSG')OR define('NO_SOCIAL_STATUS_MSG','Sorry, Community not available.');
defined('NO_TITLE_MSG')OR define('NO_TITLE_MSG','Sorry, Title not available.');
defined('NO_OCCUPATION_MSG')OR define('NO_OCCUPATION_MSG','Sorry, Occupation not available.');
defined('NO_COUNTRY_MSG')OR define('NO_COUNTRY_MSG','Sorry, Country not available.');
defined('NO_STATE_MSG')OR define('NO_STATE_MSG','Sorry, State not available.');
defined('NO_CITY_MSG')OR define('NO_CITY_MSG','Sorry, City not available.');
defined('NO_DISTRICT_MSG')OR define('NO_DISTRICT_MSG','Sorry, District not available.');
defined('NO_BOARD_MSG')OR define('NO_BOARD_MSG','Sorry, Board not available.');
defined('NO_USER_MARKING_SCHEME_MSG')OR define('NO_USER_MARKING_SCHEME_MSG','Sorry, Marking Scheme not available.');
defined('NO_YOP_STATUS')OR define('NO_YOP_STATUS','Sorry, Year of passing not available.');
defined('NO_CAMPUS_MSG')OR define('NO_CAMPUS_MSG','Sorry, Campus not available.');
defined('NO_PROGRAM_MSG')OR define('NO_PROGRAM_MSG','Sorry, Program not available.');
defined('NO_COURSE_MSG')OR define('NO_COURSE_MSG','Sorry, Course not available.');
defined('NO_UNIVERSITY_MSG')OR define('NO_UNIVERSITY_MSG','Sorry, University not available.');
defined('NO_BANKS_MSG')OR define('NO_BANKS_MSG','Sorry, Banks not available.');
defined('NO_CURRENT_QUALIFICATION_STATUS')OR define('NO_CURRENT_QUALIFICATION_STATUS','Sorry, Current Qualification Status not available');
defined('NO_SPL_PREFERENCE_COURSE_MSG')OR define('NO_SPL_PREFERENCE_COURSE_MSG','No Specializatio Preference not available');
defined('NO_QUALIFYING_DEGREE_MSG')OR define('NO_QUALIFYING_DEGREE_MSG','Sorry, Qualifying Degree not available.');
defined('NO_QUALIFYING_SPL_DEGREE_MSG')OR define('NO_QUALIFYING_SPL_DEGREE_MSG','Sorry, Qualifying Specialization Degree not available.');
defined('NO_WORKING_PLACE_MSG')OR define('NO_WORKING_PLACE_MSG','Sorry,Working Place not available.');
defined('NO_COMP_EXAM_MSG')OR define('NO_COMP_EXAM_MSG','Sorry, Competitive Exams not available.');
defined('NO_MODE_STUDY_MSG')OR define('NO_MODE_STUDY_MSG','Sorry, Mode of Study not available.');
defined('NO_STREAM_MSG')OR define('NO_STREAM_MSG','Sorry, Stream not available.');
defined('NO_DEGREE_MSG')OR define('NO_DEGREE_MSG','Sorry, Degree not available.');
defined('NO_ND_MSG')OR define('NO_ND_MSG','Sorry, Nature Of Deformity not available.');
defined('NO_PD_MSG')OR define('NO_PD_MSG','Sorry, Percentage Of Deformity not available.');
defined('NO_SC_MSG')OR define('NO_SC_MSG','Sorry, Support Center not available.');

/** alerts**/
/** 06-08-2020**/
/** 06-08-2020**/
/** AFIH 06-08-2020**/
defined('REQD_EDU_AFTER_SSLC_QUAL_MSG')OR define('REQD_EDU_AFTER_SSLC_QUAL_MSG','Please Select Qualification');
defined('REQD_CRRI_COMP_DATE_MSG')OR define('REQD_CRRI_COMP_DATE_MSG','Please Pick Date of CRRI Completion Date');
defined('REQD_REG_DATE_MSG')OR define('REQD_REG_DATE_MSG','Please Pick Date of Registration');
defined('REQD_UPLOAD_MBBS_MARKSHEET_MSG')OR define('REQD_UPLOAD_MBBS_MARKSHEET_MSG','Please upload MBBS marksheet');
defined('REQD_UPLOAD_CRRI_SHEET_MSG')OR define('REQD_UPLOAD_CRRI_SHEET_MSG','Please upload MCI Registration certificate');
defined('REQD_UPLOAD_WORK_EXP_SHEET_MSG')OR define('REQD_UPLOAD_WORK_EXP_SHEET_MSG','Please upload WORK experience certificate');
defined('REQD_UPLOAD_CRRI_SHEET_MSG')OR define('REQD_UPLOAD_CRRI_SHEET_MSG','Please upload CRRI Certificate');
defined('DECLARATION_AFIH')OR define('DECLARATION_AFIH','I here declare that the entries filled by me in this application form are correct to the best of my knowledge.I understand that the decision of the University is final in regard to the selection for admission.I promise to abide by the rules and regulations of the University and the guidelines given in the Information Booklet-2018.The University shall have the right to excep me from the Univeristy is undesirable.I agree that all disputes are subjects to the jurisdiction of the courts at Sonepat(Haryana) only.');

// Added By A2557
defined('SOMETHING_WENT_WRONG')OR define('SOMETHING_WENT_WRONG','Something went to wrong.Please try again later.');
defined('PROGRESS_INITIAL')OR define('PROGRESS_INITIAL','0%');
defined('LAST_NAME_ALLOW_DOT')OR define('LAST_NAME_ALLOW_DOT','Use . (dot), if you have no last name.');

// Form Wizard Button Values
// Added By A2557
defined('FORM_SUBMIT_VALUE')OR define('FORM_SUBMIT_VALUE','Submit');
defined('WIZARD_NEXT')OR define('WIZARD_NEXT','Next');
defined('WIZARD_PREVIOUS')OR define('WIZARD_PREVIOUS','Previous');

// Print Related Constant Header CSS Files
/*defined('HTML_OPEN')OR define('HTML_OPEN','<html><head><link href="assets/common/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" /><link rel="stylesheet" href="assets/common/css/custom.css" > <link href="assets/common/css/icons.min.css" rel="stylesheet" type="text/css"/><link href="assets/common/css/bootstrap.min.css" rel="stylesheet"   type="text/css" /><link href="assets/common/css/print.css" rel="stylesheet" type="text/css" /></head><body class="print_body" onload="window.print()">');
defined('HTML_CLOSE')OR define('HTML_CLOSE','</body></html>');
defined('PRINT_IS_TRUE')OR define('PRINT_IS_TRUE','print=yes');*/

// Print Related Constant Header CSS Files
define('PREVIEW_PRINT_URL1', APP_URL."assets/common/css/app.min.css");
define('PREVIEW_PRINT_URL2', APP_URL."assets/common/css/custom.css");
define('PREVIEW_PRINT_URL3', APP_URL."assets/common/css/icons.min.css");
define('PREVIEW_PRINT_URL4', APP_URL."assets/common/css/bootstrap.min.css");
define('PREVIEW_PRINT_URL5', APP_URL."assets/common/css/print.css");
defined('HTML_OPEN')OR define('HTML_OPEN','<html><head><link href="'.PREVIEW_PRINT_URL1.'" id="app-style" rel="stylesheet" type="text/css" /><link rel="stylesheet" href="'.PREVIEW_PRINT_URL2.'" > <link href="'.PREVIEW_PRINT_URL3.'" rel="stylesheet" type="text/css"/><link href="'.PREVIEW_PRINT_URL4.'" rel="stylesheet"   type="text/css" /><link href="'.PREVIEW_PRINT_URL5.'" rel="stylesheet" type="text/css" /></head><body class="print_body" onload="window.print()">');
defined('HTML_CLOSE')OR define('HTML_CLOSE','</body></html>');
defined('PRINT_IS_TRUE')OR define('PRINT_IS_TRUE','print=yes');

// A2557 Phd Related
defined('PHD_ABG')OR define('PHD_ABG','Academic Background (Start with latest degree obtained)');
defined('NO_CE_NEED_ENTRANCE')OR define('NO_CE_NEED_ENTRANCE','You have to write SRM ENTRANCE to qualify.');
defined('RESEARCH_SV_AVAILABLE')OR define('RESEARCH_SV_AVAILABLE','
If the Research Supervisor available at the concerned department in SRM Institute of Science and Technology are known, the choice of preference of the Supervisor- (tentative) shall be indicated (*Supervisor will be fixed by the Research Coordinating Committee)');
defined('DECLARATION_PHD')OR define('DECLARATION_PHD','This is to certify that the particulars given above are true, correct and complete to best of my knowledge and belief.');

// A2557 DDE Related
defined('GUIDELINES_DDE')OR define('GUIDELINES_DDE','Please understand that as per UGC guidelines , the PCP (Person Contact Programs) and semester exams for SRMIST DDE will be conducted only within Tamil Nadu');

// CRM - ADMIN Return
defined('RETURN_ADMIN')OR define('RETURN_ADMIN',2);
defined('RETURN_USER')OR define('RETURN_USER',1);

defined('DIPLOMA_HOLDER_MSG')OR define('DIPLOMA_HOLDER_MSG','For Diploma holders: Please Select <b>other </b>option in stream column and fill with your type of diploma in others field.');

defined('SSLC_RESULT_STATUS')OR define('SSLC_RESULT_STATUS','Please Result Status');

// March Related Constant Added By 2557
defined('MARCH_COURSE_INFO')OR define('MARCH_COURSE_INFO','M.Des course is available in SRM Kattankulathur campus only.');

defined('SSLC_RESULT_STATUS')OR define('SSLC_RESULT_STATUS','Please Result Status');
defined('SSLC_RESULT_STATUS')OR define('SSLC_RESULT_STATUS','Please Result Status');
defined('SELECT_SECOND_CAMPUS_MSG')OR define('SELECT_SECOND_CAMPUS_MSG','Please select Campus Preference 2 first');
defined('BMED_CAMPUS_MSG')OR define('BMED_CAMPUS_MSG','The online application is for admission to B.Ed/M.Ed/M.Phil programmes offered in SRMIST - Kattankulathur Campus.');
defined('HSPG_EE_CAMPUS_MSG')OR define('HSPG_EE_CAMPUS_MSG','Health Science PG Is Only Available In Main Campus Kattankulathur');
defined('ATTEMPT_MSG')OR define('ATTEMPT_MSG','Only one attempt after first appearance is allowed.');
defined('REQD_SELECT_SPL_MSG')OR define('REQD_SELECT_SPL_MSG','Please Select Specialization');
